title: Hey, Welcome
author: Farhad Hossain
email: yfreelancerfarhadhossain@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hey, welcome to my page. I'm a web designer and full time learner :)

# social links
twitter_username: FarhadH90516097 # DO NOT include the @ character, or else the build will fail!
github_username:  MD-FarhadHossain # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
